name: Docker Build and Push + Security Checks

on:
  repository_dispatch:
    types: [docker-build-push, security-checks]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.client_payload.event_type == 'docker-build-push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Variables from Event Payload
        run: |
          echo "IMAGE_NAME=${{ github.event.client_payload.image_name }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Print Docker Image URL
        run: |
          echo "Docker image pushed: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

  security-checks:
    runs-on: ubuntu-latest
    if: github.event.client_payload.event_type == 'security-checks'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Variables from Event Payload
        run: |
          echo "IMAGE_NAME=${{ github.event.client_payload.image_name }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ github.token }}" >> $GITHUB_ENV

      - name: Pull Docker Image for Scanning
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install Hadolint
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks
      
      - name: Run Gitleaks
        run: |
          gitleaks detect --source . --report-format json --report-path gitleaks_report.json || true

      - name: Run Hadolint
        run: |
          hadolint Dockerfile > hadolint_report.txt || true

      - name: Scan with Grype
        run: |
          grype docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o json > grype_report.json || true

      - name: Generate SBOM with Syft
        run: |
          syft docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o json > sbom.json || true

      - name: Vulnerability Scan with Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          format: "json"
          output: "trivy_report.json"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Combine Reports
        run: |
          echo "Security Report - $(date)" > security_report.txt
          echo "\n--- Hadolint ---" >> security_report.txt
          cat hadolint_report.txt >> security_report.txt || true
          echo "\n--- Grype ---" >> security_report.txt
          cat grype_report.json >> security_report.txt || true
          echo "\n--- Syft (SBOM) ---" >> security_report.txt
          cat sbom.json >> security_report.txt || true
          echo "\n--- Trivy ---" >> security_report.txt
          cat trivy_report.json >> security_report.txt || true
          echo "\n--- Gitleaks ---" >> security_report.txt
          echo "(Report available in GitHub Actions logs)" >> security_report.txt

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security_report
          path: security_report.txt
